### ISSUE TITLE
 Please compatible with iOS 11

### ISSUE THREAD

**Issue by cailiwu55** [Nosskirneh/Lace#2]
Hello, can you compatible with iOS 11 please？

**Comment by Nosskirneh** [comment]
It’s on my todo list. I’m currently not having that much time on my hands, but it will probably happen sometime this summer.

**Comment by cailiwu55** [comment]
That’s great to know, thank you!

**Comment by leverageinventions** [comment]
Hello, any news on iOS 11 compatibility, I also like to have this functionality, thanks

**Comment by Nosskirneh** [comment]
A little late announcement but Lace 2 is now available at BigBoss.
